version: "3"
services:
    backend:
        container_name: backend
        image: backend
        restart: always
        build: .
        ports:
          - "3000:3000"
        links:
          - mongo
        env_file:
          - ./.env
        environment:
          - NODE_ENV=dev
    mongo:
        container_name: mongo
        image: mongo
        command: mongod --port 27018
        volumes:
        - ./data:/data/db
        ports:
        - '27018:27018'